#------------------------------------------------
#         3rd party hosts 
#------------------------------------------------

nginx:
  hosts:
    siconia-portal-01:
      ansible_host: 172.30.11.58
    # siconia-portal-02:
    #   ansible_host: 172.31.14.95
    # siconia-nginx-common:
    #   ansible_host: 172.31.14.92

postgres:
  hosts:
    siconia-pdata-edata:
      ansible_host: 172.30.11.52

elasticsearch:
  hosts:
    siconia-pdata-edata:
      ansible_host: 172.30.11.52

#################################


apache-karaf:
  hosts:
    siconia-sla-kms:
      ansible_host: 172.30.11.57

kms-adapter:
  hosts:
    siconia-kms-adapter:
      ansible_host: 172.30.11.59

vsdc:
  hosts:
    siconia-vsdc-be:
      ansible_host: 172.30.11.55
    siconia-vsdc-fe:
      ansible_host: 172.30.11.54

 

      
